# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo B-side"
license = "MIT"
licenselink = "https://github.com/fisodd/hugo-b-side/blob/master/LICENSE"
description = "A clean, responsive theme using reStructuredText markup to accomplish a 2-column main-and-margin page layout."
homepage = "http://github.com/fisodd/hugo-b-side"
tags = ["restructuredtext", "responsive"]
features = ["sidebar"]
min_version = 0.20

[author]
  name = "Alexander Carlton"
  homepage = "https://www.fisodd.com/"

